
package gui;

import control.masterBarang;
import control.utama;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author meri
 */
public class frmInputBarang extends javax.swing.JDialog {
    masterBarang mb;
    utama ut;
    /**
     * Creates new form frmInputBarang
     */
    public frmInputBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ut = new utama();
        this.setLocationRelativeTo(null);
        mb = new masterBarang();
        tampil();
       
    }

    public void tampil(){
        jTable1.setModel(mb.modelBarang);
        mb.modelBarang.setRowCount(0);
        mb.tampil();
    }
    public void clear(){
        txtharga.setText("");
        txkode.setText("");
        txstok.setText("");
        txnama.setText("");
        txtketerangan.setText("");
        jTable1.clearSelection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txkode = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        txstok = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtketerangan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(176, 105, 25));
        kGradientPanel1.setkStartColor(new java.awt.Color(6, 125, 103));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_document_40px.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 122, 36));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Stok", "Harga", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 153));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 540, 360));

        jPanel2.setBackground(new java.awt.Color(240, 230, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_35px.png"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 122, 36));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_40px.png"))); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 122, 36));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_property_35px.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 122, 36));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_35px_1.png"))); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 122, 36));

        jPanel1.setBackground(new java.awt.Color(240, 230, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(6, 125, 103)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txkode.setEditable(false);
        txkode.setBackground(new java.awt.Color(255, 255, 255));
        txkode.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txkode.setForeground(new java.awt.Color(6, 125, 103));
        txkode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 125, 103)));
        txkode.setPreferredSize(new java.awt.Dimension(300, 30));
        txkode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txkodeKeyTyped(evt);
            }
        });
        jPanel1.add(txkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 210, 30));

        txnama.setEditable(false);
        txnama.setBackground(new java.awt.Color(255, 255, 255));
        txnama.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txnama.setForeground(new java.awt.Color(6, 125, 103));
        txnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 125, 103)));
        txnama.setPreferredSize(new java.awt.Dimension(300, 30));
        txnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txnamaKeyTyped(evt);
            }
        });
        jPanel1.add(txnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 210, 30));

        txstok.setEditable(false);
        txstok.setBackground(new java.awt.Color(255, 255, 255));
        txstok.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txstok.setForeground(new java.awt.Color(6, 125, 103));
        txstok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 125, 103)));
        txstok.setPreferredSize(new java.awt.Dimension(300, 40));
        txstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txstokKeyTyped(evt);
            }
        });
        jPanel1.add(txstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        txtharga.setEditable(false);
        txtharga.setBackground(new java.awt.Color(255, 255, 255));
        txtharga.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txtharga.setForeground(new java.awt.Color(6, 125, 103));
        txtharga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 125, 103)));
        txtharga.setPreferredSize(new java.awt.Dimension(300, 40));
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargaKeyTyped(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(6, 125, 103));
        jLabel9.setText("Stok");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(6, 125, 103));
        jLabel11.setText("Kode Barang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(6, 125, 103));
        jLabel12.setText("Nama Barang");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 30));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(6, 125, 103));
        jLabel13.setText("Keteragan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 30));

        txtketerangan.setEditable(false);
        txtketerangan.setBackground(new java.awt.Color(255, 255, 255));
        txtketerangan.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        txtketerangan.setForeground(new java.awt.Color(6, 125, 103));
        txtketerangan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 125, 103)));
        txtketerangan.setPreferredSize(new java.awt.Dimension(300, 40));
        txtketerangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtketeranganKeyTyped(evt);
            }
        });
        jPanel1.add(txtketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, 60));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(6, 125, 103));
        jLabel14.setText("Harga Barang");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 360));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(6, 125, 103));
        jLabel10.setText("MASUKAN / EDIT STOK BARANG");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 480));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 2, 960, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
          String kode = txkode.getText();
        try {
            mb.hapus(kode);
                   JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI HAPUS");
            tampil();
            clear();
           
        } catch (SQLException ex) {
            Logger.getLogger(frmInputBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txkode.setEditable(true);
        txnama.setEditable(true);
        txstok.setEditable(true);
        txtharga.setEditable(true);
        txtketerangan.setEditable(true);
        btnSimpan.setEnabled(true);
        btnCancel.setEnabled(true);
        btnNew.setEnabled(false);
        txkode.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txkode.setEditable(false);
        txnama.setEditable(false);
        txtharga.setEditable(false);
        txstok.setEditable(false);
        txtketerangan.setEnabled(false);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnCancel.setEnabled(false);
        btnNew.setEnabled(true);
        clear();
        jTable1.clearSelection();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        edit = true;
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnSimpan.setEnabled(true);
        txnama.setEditable(true);
        txstok.setEditable(true);
        txtharga.setEditable(true);
        txtketerangan.setEditable(true);
        txnama.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed
        boolean edit = false;
        
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      
        if(edit==true){
        String kode = txkode.getText();
        String nama = txnama.getText();
        String keterangan = txtketerangan.getText();
        int stok = Integer.parseInt(txstok.getText());
        int harga = Integer.parseInt(txtharga.getText());
        
        try {
            mb.edit(kode, nama, stok, harga,keterangan);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI UPDATE");
            tampil();
            clear();
            txkode.setEditable(false);
            txnama.setEditable(false);
            txstok.setEditable(false);
            txtharga.setEditable(false);
            txtketerangan.setEditable(false);
            btnSimpan.setEnabled(false);
            btnCancel.setEnabled(false);
            btnNew.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(frmInputBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }else{
            String kode = txkode.getText();
            String nama = txnama.getText();
            String keterangan = txtketerangan.getText();
            int stok = Integer.parseInt(txstok.getText());
            int harga = Integer.parseInt(txtharga.getText());
        try {
            mb.simpan(kode, nama, stok, harga, keterangan);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DISIMPAN");
            tampil();
            
            clear();
            btnSimpan.setEnabled(false);
            btnCancel.setEnabled(false);
            btnNew.setEnabled(true);
            txkode.setEditable(false);
            txnama.setEditable(false);
            txstok.setEditable(false);
            txtharga.setEditable(false);
            txtketerangan.setEditable(false);
            btnSimpan.setEnabled(false);
            btnCancel.setEnabled(false);
            btnNew.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmInputBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
      
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int row = jTable1.getSelectedRow();
        txkode.setText(jTable1.getValueAt(row, 0).toString());
        txnama.setText(jTable1.getValueAt(row, 1).toString());
        txstok.setText(jTable1.getValueAt(row, 2).toString());
        txtharga.setText(jTable1.getValueAt(row, 3).toString());
        txtketerangan.setText(jTable1.getValueAt (row,4).toString());
        
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        ut.tampilCountBrg();
        ut.tampilCountPlg();
        ut.tampilCountTrx();
    }//GEN-LAST:event_formWindowClosing

    private void txkodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txkodeKeyTyped
        
        if(txkode.getText().length()==30){
            evt.consume();
        }
    }//GEN-LAST:event_txkodeKeyTyped

    private void txnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnamaKeyTyped
        
        if(txnama.getText().length()==50){
            evt.consume();
        }
    }//GEN-LAST:event_txnamaKeyTyped

    private void txstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txstokKeyTyped
        
        if(txstok.getText().length()==6){
            evt.consume();
        }
    }//GEN-LAST:event_txstokKeyTyped

    private void txthargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyTyped
        
        if(txtharga.getText().length()==50){
            evt.consume();
        }
    }//GEN-LAST:event_txthargaKeyTyped

    private void txtketeranganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtketeranganKeyTyped
       
        if(txtketerangan.getText().length()==50){
            evt.consume();
    }//GEN-LAST:event_txtketeranganKeyTyped
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCariBarang dialog = new frmCariBarang(new javax.swing.JFrame(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    public static javax.swing.JTextField txkode;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txstok;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtketerangan;
    // End of variables declaration//GEN-END:variables
}
