
package gui;

import control.laporan;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author meri
 */
public class frmLaporan extends javax.swing.JDialog {
laporan lp;

    /**
     * Creates new form frmLaporan
     */
    public frmLaporan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lp = new laporan();
        setLocationRelativeTo(null);
        lp.tampailBarangTerjual();
        tanggall();
        lp.tampilPendapatanHariIni(tgli.getText());
        lp.tampilTotal();
        lp.grafik();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        brgTerjual = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        pendapatanHariini = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        txTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tgli = new javax.swing.JLabel();
        chart = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 230, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(176, 105, 25)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(57, 174, 186));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(104, 240, 166));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barang Terjual");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        brgTerjual.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        brgTerjual.setForeground(new java.awt.Color(255, 255, 255));
        brgTerjual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        brgTerjual.setText("0");
        kGradientPanel1.add(brgTerjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 176, 30));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 70));

        kGradientPanel2.setkEndColor(new java.awt.Color(176, 212, 34));
        kGradientPanel2.setkGradientFocus(400);
        kGradientPanel2.setkStartColor(new java.awt.Color(176, 105, 25));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pendapatan Hari Ini");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pendapatanHariini.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pendapatanHariini.setForeground(new java.awt.Color(255, 255, 255));
        pendapatanHariini.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pendapatanHariini.setText("0");
        kGradientPanel2.add(pendapatanHariini, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 32, 135, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Rp.");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, 30));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 70));

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 141, 66));
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 194, 179));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Pendapatan");
        kGradientPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txTotal.setForeground(new java.awt.Color(255, 255, 255));
        txTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txTotal.setText("0");
        kGradientPanel3.add(txTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 31, 147, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Rp.");
        kGradientPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, 30));

        jPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 210, 70));

        tgli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tgli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, 36));

        chart.setBackground(new java.awt.Color(255, 255, 255));
        chart.setLayout(new java.awt.BorderLayout());
        jPanel1.add(chart, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 700, 240));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_print_50px.png"))); // NOI18N
        jButton1.setText("CETAK LAPORAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, 40));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(6, 125, 103));
        jLabel6.setText("LAPORAN KEUANGAN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String tanggalCetak = format.format(date);
        lp.printLap(tanggalCetak);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
    public void run() {
        frmLaporan dialog = new frmLaporan(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
    
    public void windowClosing(java.awt.event.WindowEvent e) {
        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void tanggall(){
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        tgli.setText(format.format(date));
        tgli.setVisible(false);
       
    }
//    public void grafik(){
//        DefaultCategoryDataset obj = new DefaultCategoryDataset();
//        obj.setValue(20, "24-03-2020", "HARI");
//        obj.setValue(40, "25-03-2020", "HARI");
//        obj.setValue(30, "26-03-2020", "HARI");
//        JFreeChart chart = ChartFactory.createBarChart("GRAFIK PENJUALAN", "ASS", "KONTOL", obj,PlotOrientation.VERTICAL,false,true,false);
//        CategoryPlot  objc = chart.getCategoryPlot();
//        objc.setRangeGridlinePaint(Color.black);
//        objc.setBackgroundPaint(Color.white);
//        
//       ChartPanel panel = new ChartPanel(chart);
//       frmLaporan.chart.removeAll();
//       frmLaporan.chart.add(panel,BorderLayout.CENTER);
//       frmLaporan.chart.validate();
//    }
//      
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel brgTerjual;
    public static javax.swing.JPanel chart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    public static javax.swing.JLabel pendapatanHariini;
    private javax.swing.JLabel tgli;
    public static javax.swing.JLabel txTotal;
    // End of variables declaration//GEN-END:variables
}
