
package gui;


import control.pelanggan;
import control.utama;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author meri
 */
public class frmPelanggan extends javax.swing.JDialog {
    pelanggan pl;
    utama ut;
    
    /**
     * Creates new form frmInputBarang
     */
    public frmPelanggan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ut = new utama();
        this.setLocationRelativeTo(null);
        pl = new pelanggan();
        tampil();
       
    }

    public void tampil(){
        jTable1.setModel(pl.model);
        pl.model.setRowCount(0);
        pl.tampil();
    }
    public void clear(){
        txnomor.setText("");
        txid.setText("");
        txalamat.setText("");
        txnama.setText("");
        jTable1.clearSelection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txid = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txalamat = new javax.swing.JTextField();
        txnomor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(957, 522));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(225, 205, 92));
        kGradientPanel1.setkStartColor(new java.awt.Color(6, 125, 103));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(957, 522));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 230, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(6, 125, 103)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 125, 103));
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txid.setEditable(false);
        txid.setBackground(new java.awt.Color(255, 255, 255));
        txid.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txid.setForeground(new java.awt.Color(6, 125, 103));
        txid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txidKeyTyped(evt);
            }
        });
        jPanel1.add(txid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 252, 29));

        txnama.setEditable(false);
        txnama.setBackground(new java.awt.Color(255, 255, 255));
        txnama.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txnama.setForeground(new java.awt.Color(6, 125, 103));
        txnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txnamaKeyTyped(evt);
            }
        });
        jPanel1.add(txnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 252, 29));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 125, 103));
        jLabel2.setText("Id ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 125, 103));
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txalamat.setEditable(false);
        txalamat.setBackground(new java.awt.Color(255, 255, 255));
        txalamat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txalamat.setForeground(new java.awt.Color(6, 125, 103));
        txalamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txalamatKeyTyped(evt);
            }
        });
        jPanel1.add(txalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 252, 29));

        txnomor.setEditable(false);
        txnomor.setBackground(new java.awt.Color(255, 255, 255));
        txnomor.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txnomor.setForeground(new java.awt.Color(6, 125, 103));
        txnomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txnomorKeyTyped(evt);
            }
        });
        jPanel1.add(txnomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 252, 29));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 125, 103));
        jLabel4.setText("No. Tlp");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 340, 340));

        jPanel2.setBackground(new java.awt.Color(240, 230, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_document_40px.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 122, 36));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_35px.png"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 122, 36));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_40px.png"))); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 122, 36));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_property_35px.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 122, 36));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_35px_1.png"))); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 122, 36));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PELANGGAN", "NAMA PELANGGAN", "ALAMAT", "NO TELEPON"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 153));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 470, 340));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(6, 125, 103));
        jLabel10.setText("ISI DATA PELANGGAN");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 860, 480));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -6, 890, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        
        String kode = txid.getText();
        try {
            pl.hapus(kode);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI HAPUS");
            tampil();
            clear();
           
        } catch (SQLException ex) {
            Logger.getLogger(frmPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        
        txid.setEditable(true);
        txnama.setEditable(true);
        txalamat.setEditable(true);
        txnomor.setEditable(true);
        btnSimpan.setEnabled(true);
        btnCancel.setEnabled(true);
        btnNew.setEnabled(false);
        txid.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        txid.setEditable(false);
        txnama.setEditable(false);
        txalamat.setEditable(false);
        txnomor.setEditable(false);
        btnSimpan.setEnabled(false);
        btnCancel.setEnabled(false);
        btnHapus.setEnabled(false);
        btnEdit.setEnabled(false);
        btnNew.setEnabled(true);
        clear();
        jTable1.clearSelection();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        edit = true;
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnSimpan.setEnabled(true);
        txnama.setEditable(true);
        txalamat.setEditable(true);
        txnomor.setEditable(true);
        txnama.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed
        boolean edit = false;
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        
        if(edit==true){
            String idpelanggan = txid.getText();
            String nama = txnama.getText();
            String alamat = txalamat.getText();
            String nomor = txnomor.getText();
            try {
                pl.edit(idpelanggan, nama, alamat, nomor);
                 JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI UPDATE");
                tampil();
                clear();
                txid.setEditable(false);
                txnama.setEditable(false);
                txalamat.setEditable(false);
                txnomor.setEditable(false);
                btnSimpan.setEnabled(false);
                btnCancel.setEnabled(false);
                btnNew.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmPelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
         String idpelanggan = txid.getText();
         String nama = txnama.getText();
         String alamat = txalamat.getText();
         String nomor = txnomor.getText();
         
        try {
            pl.simpan(idpelanggan, nama, alamat, nomor);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DISIMPAN");
            tampil();
            
            clear();
            btnSimpan.setEnabled(false);
            btnCancel.setEnabled(false);
            btnNew.setEnabled(true);
            txid.setEditable(false);
            txnama.setEditable(false);
            txalamat.setEditable(false);
            txnomor.setEditable(false);
            btnSimpan.setEnabled(false);
            btnCancel.setEnabled(false);
            btnNew.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int row = jTable1.getSelectedRow();
        txid.setText(jTable1.getValueAt(row, 0).toString());
        txnama.setText(jTable1.getValueAt(row, 1).toString());
        txalamat.setText(jTable1.getValueAt(row, 2).toString());
        txnomor.setText(jTable1.getValueAt(row, 3).toString());
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        ut.tampilCountBrg();
        ut.tampilCountPlg();
        ut.tampilCountTrx();
    }//GEN-LAST:event_formWindowClosing

    private void txidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txidKeyTyped
       
        if(txid.getText().length()==5){
            evt.consume();
        }
    }//GEN-LAST:event_txidKeyTyped

    private void txnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnamaKeyTyped
        
          if(txnama.getText().length()==30){
            evt.consume();
        }
    }//GEN-LAST:event_txnamaKeyTyped

    private void txalamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txalamatKeyTyped
        
          if(txalamat.getText().length()==40){
            evt.consume();
        }
    }//GEN-LAST:event_txalamatKeyTyped

    private void txnomorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txnomorKeyTyped
        
          if(txnomor.getText().length()==16){
            evt.consume();
        }
    }//GEN-LAST:event_txnomorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCariBarang dialog = new frmCariBarang(new javax.swing.JFrame(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txalamat;
    public static javax.swing.JTextField txid;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txnomor;
    // End of variables declaration//GEN-END:variables
}
