
package gui;

import control.masterBarang;
import control.user;
import control.utama;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author meri
 */
public class frmUser extends javax.swing.JDialog {
   
    utama ut;
    user ur;
    /**
     * Creates new form frmInputBarang
     */
    public frmUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ut = new utama();
        this.setLocationRelativeTo(null);
        ur = new user();
        tampil();
       
    }

    public void tampil(){
        jTable1.setModel(ur.model);
        ur.model.setRowCount(0);
        ur.tampil();
    }
    public void clear(){
        txNohp.setText("");
        txUser.setText("");
        txNama.setText("");
        txPass.setText("");
        jTable1.clearSelection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    kGradientPanel1 = new keeptoo.KGradientPanel();
    jPanel2 = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txUser = new javax.swing.JTextField();
    txPass = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txNama = new javax.swing.JTextField();
    txNohp = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    txId = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    btnHapus = new javax.swing.JButton();
    btnSimpan = new javax.swing.JButton();
    btnNew = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    jLabel10 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(957, 522));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    kGradientPanel1.setkBorderRadius(0);
    kGradientPanel1.setkEndColor(new java.awt.Color(6, 125, 103));
    kGradientPanel1.setkStartColor(new java.awt.Color(225, 205, 92));
    kGradientPanel1.setPreferredSize(new java.awt.Dimension(957, 522));
    kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(240, 230, 229));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBackground(new java.awt.Color(240, 230, 229));
    jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(6, 125, 103));
    jLabel1.setText("PASSWORD");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 137, -1, -1));

    txUser.setEditable(false);
    txUser.setBackground(new java.awt.Color(255, 255, 255));
    txUser.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
    txUser.setForeground(new java.awt.Color(225, 205, 92));
    txUser.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txUserKeyTyped(evt);
      }
    });
    jPanel1.add(txUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 102, 221, 29));

    txPass.setEditable(false);
    txPass.setBackground(new java.awt.Color(255, 255, 255));
    txPass.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
    txPass.setForeground(new java.awt.Color(225, 205, 92));
    txPass.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txPassKeyTyped(evt);
      }
    });
    jPanel1.add(txPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 157, 221, 29));

    jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(6, 125, 103));
    jLabel2.setText("USERNAME");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 82, -1, -1));

    jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(6, 125, 103));
    jLabel3.setText("NAMA");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 192, -1, -1));

    txNama.setEditable(false);
    txNama.setBackground(new java.awt.Color(255, 255, 255));
    txNama.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
    txNama.setForeground(new java.awt.Color(225, 205, 92));
    txNama.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txNamaKeyTyped(evt);
      }
    });
    jPanel1.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 212, 221, 29));

    txNohp.setEditable(false);
    txNohp.setBackground(new java.awt.Color(255, 255, 255));
    txNohp.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
    txNohp.setForeground(new java.awt.Color(225, 205, 92));
    txNohp.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txNohpKeyTyped(evt);
      }
    });
    jPanel1.add(txNohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 272, 221, 29));

    jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(6, 125, 103));
    jLabel4.setText("NO HP");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 252, -1, -1));

    txId.setEditable(false);
    txId.setBackground(new java.awt.Color(255, 255, 255));
    txId.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
    txId.setForeground(new java.awt.Color(225, 205, 92));
    txId.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txIdKeyTyped(evt);
      }
    });
    jPanel1.add(txId, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 47, 114, 29));

    jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(6, 125, 103));
    jLabel5.setText("ID");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 27, -1, -1));

    jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 310, 330));

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.setGridColor(new java.awt.Color(102, 102, 102));
    jTable1.setSelectionBackground(new java.awt.Color(0, 204, 153));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jTable1);

    jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 510, 330));

    btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_40px.png"))); // NOI18N
    btnHapus.setText("HAPUS");
    btnHapus.setEnabled(false);
    btnHapus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHapusActionPerformed(evt);
      }
    });
    jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 122, 36));

    btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_35px.png"))); // NOI18N
    btnSimpan.setText("SIMPAN");
    btnSimpan.setEnabled(false);
    btnSimpan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSimpanActionPerformed(evt);
      }
    });
    jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 122, 36));

    btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_document_40px.png"))); // NOI18N
    btnNew.setText("NEW");
    btnNew.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNewActionPerformed(evt);
      }
    });
    jPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 122, 36));

    btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_35px_1.png"))); // NOI18N
    btnCancel.setText("CANCEL");
    btnCancel.setEnabled(false);
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });
    jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 122, 36));

    btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_property_35px.png"))); // NOI18N
    btnEdit.setText("EDIT");
    btnEdit.setEnabled(false);
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });
    jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 122, 36));

    jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(225, 205, 92));
    jLabel10.setText("TAMBAH ADMIN");
    jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

    kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 480));

    getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 890, 510));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        
        String id = txId.getText();
        try {
            ur.hapus(id);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI HAPUS");
            tampil();
            clear();
           
        } catch (SQLException ex) {
            Logger.getLogger(frmUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        
        txId.setEditable(true);
        txUser.setEditable(true);
        txPass.setEditable(true);
        txNama.setEditable(true);
        txNohp.setEditable(true);
        btnSimpan.setEnabled(true);
        btnCancel.setEnabled(true);
        btnNew.setEnabled(false);
        txId.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        txUser.setEditable(false);
        txPass.setEditable(false);
        txNama.setEditable(false);
        btnHapus.setEnabled(false);
        btnEdit.setEnabled(false);
        txNohp.setEditable(false);
        btnSimpan.setEnabled(false);
        btnCancel.setEnabled(false);
        btnNew.setEnabled(true);
        clear();
        jTable1.clearSelection();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        edit = true;
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnSimpan.setEnabled(true);
        txPass.setEditable(true);
        txNama.setEditable(true);
        txNohp.setEditable(true);
        txPass.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed
        boolean edit = false;
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        
     if(edit==true){
        String id = txId.getText();
        String user = txUser.getText();
        String pass = txPass.getText();
        String nama = txNama.getText();
        String nohp = txNohp.getText();
            
    try {
          ur.edit(id,user,pass,nama,nohp);
          JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI UPDATE");
          tampil();
          clear();
          
          txUser.setEditable(false);
          txPass.setEditable(false);
          txNama.setEditable(false);
          txNohp.setEditable(false);
          btnSimpan.setEnabled(false);
          btnCancel.setEnabled(false);
          btnNew.setEnabled(true);
          
    } catch (SQLException ex) {
        Logger.getLogger(frmUser.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }else{
          String id = txId.getText();
          String user = txUser.getText();
          String pass = txPass.getText();
          String nama = txNama.getText();
          String nohp = txNohp.getText();
        try {
            ur.simpan(id, user, pass, nama, nohp);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DISIMPAN");
            tampil();
            
            clear();
            btnSimpan.setEnabled(false);
            btnCancel.setEnabled(false);
            btnNew.setEnabled(true);
            txUser.setEditable(false);
            txPass.setEditable(false);
            txNama.setEditable(false);
            txNohp.setEditable(false);
            btnSimpan.setEnabled(false);
            btnCancel.setEnabled(false);
            btnNew.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmUser.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        int row = jTable1.getSelectedRow();
        txId.setText(jTable1.getValueAt(row, 0).toString());
        txUser.setText(jTable1.getValueAt(row, 1).toString());
        txPass.setText(jTable1.getValueAt(row, 2).toString());
        txNama.setText(jTable1.getValueAt(row, 3).toString());
        txNohp.setText(jTable1.getValueAt(row, 4).toString());
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        ut.tampilCountBrg();
        ut.tampilCountPlg();
        ut.tampilCountTrx();
    }//GEN-LAST:event_formWindowClosing

    private void txkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txkodeActionPerformed
       
    }//GEN-LAST:event_txkodeActionPerformed

    private void txUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txUserKeyTyped
        
          if(txUser.getText().length()==16){
            evt.consume();
        }
    }//GEN-LAST:event_txUserKeyTyped

    private void txPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPassKeyTyped
       
        if(txPass.getText().length()==16){
            evt.consume();
        }
    }//GEN-LAST:event_txPassKeyTyped

    private void txNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNamaKeyTyped
       
        if(txNama.getText().length()==30){
            evt.consume();
        }
    }//GEN-LAST:event_txNamaKeyTyped

    private void txNohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNohpKeyTyped
        
        if(txNohp.getText().length()==16){
            evt.consume();
        }
    }//GEN-LAST:event_txNohpKeyTyped

    private void txIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txIdKeyTyped
        
        if(txId.getText().length()==5){
            evt.consume();
        }
    }//GEN-LAST:event_txIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCariBarang dialog = new frmCariBarang(new javax.swing.JFrame(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnHapus;
  private javax.swing.JButton btnNew;
  private javax.swing.JButton btnSimpan;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private keeptoo.KGradientPanel kGradientPanel1;
  public static javax.swing.JTextField txId;
  private javax.swing.JTextField txNama;
  private javax.swing.JTextField txNohp;
  private javax.swing.JTextField txPass;
  public static javax.swing.JTextField txUser;
  // End of variables declaration//GEN-END:variables
}
