/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ASUS
 */
public class menu_infotanaman extends javax.swing.JFrame {

    /**
     * Creates new form menu_infotanaman
     */
    public menu_infotanaman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        shop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cabaimerah = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jeruknipis = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kunyit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aloe = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lidahmertua = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        timun = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tomat = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pandan = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sirih = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        kemangi = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        serai = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        peacelily = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logout1 = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 238, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(6, 125, 103)));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 475));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shop.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        shop.setForeground(new java.awt.Color(6, 125, 103));
        shop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        shop.setText("INFO TANAMAN");
        jPanel2.add(shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 11, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 5, 5, 5, new java.awt.Color(6, 125, 103)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(778, 300));

        jPanel1.setBackground(new java.awt.Color(244, 238, 238));
        jPanel1.setMinimumSize(new java.awt.Dimension(793, 624));
        jPanel1.setPreferredSize(new java.awt.Dimension(793, 624));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabaimerah.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        cabaimerah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cabaimerah.jpg"))); // NOI18N
        cabaimerah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cabaimerahMouseClicked(evt);
            }
        });
        jPanel1.add(cabaimerah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 140));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 149, 36));
        jLabel7.setText("CABAI MERAH");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, -1));

        jeruknipis.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jeruknipis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/jeruknipis.jpg"))); // NOI18N
        jeruknipis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jeruknipisMouseClicked(evt);
            }
        });
        jPanel1.add(jeruknipis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 140));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 149, 36));
        jLabel3.setText("JERUK NIPIS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, -1));

        kunyit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        kunyit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kunyit.jpg"))); // NOI18N
        kunyit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kunyitMouseClicked(evt);
            }
        });
        jPanel1.add(kunyit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 140));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 149, 36));
        jLabel4.setText("KUNYIT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 60, 20));

        aloe.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        aloe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/aloe.jpg"))); // NOI18N
        aloe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aloeMouseClicked(evt);
            }
        });
        jPanel1.add(aloe, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, 140));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 149, 36));
        jLabel12.setText("LIDAH BUAYA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 110, 20));

        lidahmertua.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lidahmertua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lidahmertua.jpg"))); // NOI18N
        lidahmertua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lidahmertuaMouseClicked(evt);
            }
        });
        jPanel1.add(lidahmertua, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 140));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 149, 36));
        jLabel14.setText("LIDAH MERTUA");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        timun.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        timun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mentimun.jpg"))); // NOI18N
        timun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timunMouseClicked(evt);
            }
        });
        jPanel1.add(timun, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, 140));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 149, 36));
        jLabel16.setText("MENTIMUN");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 90, -1));

        tomat.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        tomat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tomatt.jpg"))); // NOI18N
        tomat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tomatMouseClicked(evt);
            }
        });
        jPanel1.add(tomat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 140));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 149, 36));
        jLabel18.setText("TOMAT");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 60, -1));

        pandan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        pandan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pandan.jpg"))); // NOI18N
        pandan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pandanMouseClicked(evt);
            }
        });
        jPanel1.add(pandan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, 140));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(238, 149, 36));
        jLabel20.setText("PANDAN");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        sirih.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        sirih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/daunsirih.jpg"))); // NOI18N
        sirih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sirihMouseClicked(evt);
            }
        });
        jPanel1.add(sirih, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 140));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 149, 36));
        jLabel22.setText("DAUN SIRIH");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        kemangi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        kemangi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kemangi.jpg"))); // NOI18N
        kemangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kemangiMouseClicked(evt);
            }
        });
        jPanel1.add(kemangi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, 140));

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(238, 149, 36));
        jLabel24.setText("KEMANGI");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 80, -1));

        serai.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        serai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/serai.jpg"))); // NOI18N
        serai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seraiMouseClicked(evt);
            }
        });
        jPanel1.add(serai, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, 140));

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(238, 149, 36));
        jLabel26.setText("SERAI");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 60, -1));

        peacelily.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        peacelily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/peacelily.png"))); // NOI18N
        peacelily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peacelilyMouseClicked(evt);
            }
        });
        jPanel1.add(peacelily, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, 140));

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(238, 149, 36));
        jLabel28.setText("PEACE LILY");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 820, -1));

        jPanel3.setBackground(new java.awt.Color(6, 125, 103));
        jPanel3.setPreferredSize(new java.awt.Dimension(820, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jPanel3.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
        });
        jPanel3.add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 429, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cabaimerahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabaimerahMouseClicked
        new info_cabaimerah().setVisible(true);
    }//GEN-LAST:event_cabaimerahMouseClicked

    private void jeruknipisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeruknipisMouseClicked
        new info_jeruknipis().setVisible(true);
    }//GEN-LAST:event_jeruknipisMouseClicked

    private void kunyitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kunyitMouseClicked
        new info_kunyit().setVisible(true);
    }//GEN-LAST:event_kunyitMouseClicked

    private void aloeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aloeMouseClicked
        new info_aloe().setVisible(true);
    }//GEN-LAST:event_aloeMouseClicked

    private void lidahmertuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lidahmertuaMouseClicked
        new info_lidahmertua().setVisible(true);
    }//GEN-LAST:event_lidahmertuaMouseClicked

    private void timunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timunMouseClicked
        new info_mentimun().setVisible(true);
    }//GEN-LAST:event_timunMouseClicked

    private void tomatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomatMouseClicked
        new info_tomat().setVisible(true);
    }//GEN-LAST:event_tomatMouseClicked

    private void pandanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pandanMouseClicked
        new info_daunpandan().setVisible(true);
    }//GEN-LAST:event_pandanMouseClicked

    private void sirihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sirihMouseClicked
       new info_daunsirih().setVisible(true);
    }//GEN-LAST:event_sirihMouseClicked

    private void kemangiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kemangiMouseClicked
        new info_kemangi().setVisible(true);
    }//GEN-LAST:event_kemangiMouseClicked

    private void seraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seraiMouseClicked
        new info_serai().setVisible(true);
    }//GEN-LAST:event_seraiMouseClicked

    private void peacelilyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peacelilyMouseClicked
        new info_lily().setVisible(true);
    }//GEN-LAST:event_peacelilyMouseClicked

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
        new menu_pelanggan().setVisible(true);
    }//GEN-LAST:event_home1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_infotanaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_infotanaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_infotanaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_infotanaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_infotanaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aloe;
    private javax.swing.JLabel cabaimerah;
    private javax.swing.JLabel home1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jeruknipis;
    private javax.swing.JLabel kemangi;
    private javax.swing.JLabel kunyit;
    private javax.swing.JLabel lidahmertua;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel pandan;
    private javax.swing.JLabel peacelily;
    private javax.swing.JLabel serai;
    private javax.swing.JLabel shop;
    private javax.swing.JLabel sirih;
    private javax.swing.JLabel timun;
    private javax.swing.JLabel tomat;
    // End of variables declaration//GEN-END:variables
}
