
package gui;

import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author meri
 */
public class menu_produk extends javax.swing.JFrame {

    /** Creates new form menu_shop */
    public menu_produk() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_menu = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        perawatantanaman = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logout1 = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(244, 238, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(135, 142, 108)));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 475));

        perawatantanaman.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        perawatantanaman.setForeground(new java.awt.Color(135, 142, 108));
        perawatantanaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop.png"))); // NOI18N
        perawatantanaman.setText("PRODUK");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(135, 142, 108)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(820, 298));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(778, 1570));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 1335));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_setalat.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 100, 100));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setText("PERLENGKAPAN BERCOCOK TANAM");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 390, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 420, 5));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("   Rp. 100.000");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, 20));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pot3.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, 100));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pot2.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 100, 100));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_potgantung.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 100, 100));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pot4.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 100, 100));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_penyiram.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 100));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pot1.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 100));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel14.setText(" POT HITAM");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 20));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel15.setText(" POT BIRU");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 60, 20));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel16.setText(" Rp. 99.000");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 70, 20));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel17.setText("  POT COKLAT");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 20));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel18.setText("   Rp. 150.000");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 90, 20));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel19.setText(" POT GANTUNG");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 100, 20));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel20.setText(" Rp. 80.000");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 70, 20));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel21.setText("POT PUTIH");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 70, 20));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel22.setText("   Rp. 215.000");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 90, 20));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel23.setText("PENYIRAM TANAMAN");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 20));

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel24.setText(" Rp. 99.000");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 70, 20));

        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel25.setText(" SET ALAT BERKEBUN");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 130, 20));

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel26.setText(" Rp. 55.000");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 70, 20));

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel27.setText("BENIH & BIBIT TANAMAN");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 270, 50));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 310, 5));

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_bibitdaunbawang.jpg"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 100, 100));

        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel29.setText("BENIH DAUN BAWANG");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 150, 20));

        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel30.setText(" Rp. 12.000");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 680, 70, 20));

        jLabel31.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_bibittomat.png"))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 100, 100));

        jLabel32.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel32.setText(" BENIH TOMAT");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 90, 20));

        jLabel33.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel33.setText(" Rp. 15.000");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 680, 70, 20));

        jLabel34.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_bibitkangkung.jpg"))); // NOI18N
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 100, 100));

        jLabel35.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel35.setText("BENIH KANGKUNG");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, -1, 20));

        jLabel36.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel36.setText(" Rp. 10.000");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 70, 20));

        jLabel37.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_bibitbawangmerah.jpg"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 100, 100));

        jLabel38.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel38.setText("BENIH BAWANG MERAH");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 150, 20));

        jLabel39.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel39.setText(" Rp. 12.000");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 680, 70, 20));

        jLabel40.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel40.setText(" BENIH CABAI");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 90, 20));

        jLabel41.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_bibitcabe.jpg"))); // NOI18N
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 100, 100));

        jLabel42.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel42.setText(" Rp. 15.000");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 680, 70, 20));

        jLabel43.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_daunpandan.jpg"))); // NOI18N
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 100, 100));

        jLabel44.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel44.setText(" BIBIT DAUN PANDAN");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, -1, 20));

        jLabel45.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel45.setText(" Rp. 20.000");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 870, 70, 20));

        jLabel46.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_jeruknipis.jpg"))); // NOI18N
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 740, 100, 100));

        jLabel47.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel47.setText(" BIBIT JERUK NIPIS");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 850, 120, 20));

        jLabel48.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel48.setText(" Rp. 20.000");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 870, 70, 20));

        jLabel49.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_lidahbuaya.jpg"))); // NOI18N
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 740, 100, 100));

        jLabel50.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel50.setText("BIBIT LIDAH BUAYA");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 850, 120, 20));

        jLabel51.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel51.setText(" Rp. 15.000");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 870, 70, 20));

        jLabel52.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel52.setText(" Rp. 10.000");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 870, 70, 20));

        jLabel53.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel53.setText("BIBIT LIDAH MERTUA");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 850, 130, 20));

        jLabel54.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_lidahmertua.jpg"))); // NOI18N
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 740, 100, 100));

        jLabel55.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_phtanah.jpg"))); // NOI18N
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 100, 100));

        jLabel56.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel56.setText("PENGUKUR PH TANAH");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 140, 20));

        jLabel57.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel57.setText(" Rp. 75.000");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 70, 20));

        jLabel58.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel58.setText(" PUPUK & MEDIA TANAM");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 920, 270, 50));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 960, 310, 5));

        jLabel59.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pupukKNO3merah.jpg"))); // NOI18N
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1010, 100, 100));

        jLabel60.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel60.setText(" PUPUK KNO3 MERAH");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1120, 140, 20));

        jLabel61.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel61.setText(" Rp. 47.500");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1140, 70, 20));

        jLabel62.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pupukKNO3putih.jpg"))); // NOI18N
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1010, 100, 100));

        jLabel63.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel63.setText("PUPUK KNO3 PUTIH");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1120, 130, 20));

        jLabel64.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel64.setText(" Rp. 52.500");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1140, 70, 20));

        jLabel65.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pupukhidroponik1.jpg"))); // NOI18N
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1010, 100, 100));

        jLabel66.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel66.setText("PUPUK HIDROPONIK");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1120, -1, 20));

        jLabel67.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel67.setText(" Rp. 19.000");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1140, 70, 20));

        jLabel68.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_pupukhidroponik2.jpg"))); // NOI18N
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1010, 100, 100));

        jLabel69.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel69.setText("PUPUK HIDROPONIK CABAI");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1120, 170, 20));

        jLabel70.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel70.setText(" Rp. 19.000");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1140, 70, 20));

        jLabel71.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_mediatanam.jpg"))); // NOI18N
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1010, 100, 100));

        jLabel72.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel72.setText("MEDIA TANAM (15 Kg)");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 1120, -1, 20));

        jLabel73.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel73.setText(" Rp. 25.000");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1140, 70, 20));

        jLabel74.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop/shop_tanah.png"))); // NOI18N
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1170, 100, 100));

        jLabel75.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel75.setText("TANAH (17 Kg)");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1280, 100, 20));

        jLabel76.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel76.setText(" Rp. 20.000");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1300, 70, 20));

        jScrollPane1.setViewportView(jPanel1);

        jPanel3.setBackground(new java.awt.Color(135, 142, 108));
        jPanel3.setPreferredSize(new java.awt.Dimension(820, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jPanel3.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
        });
        jPanel3.add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(perawatantanaman)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(perawatantanaman)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
        new menu_pelanggan().setVisible(true);
    }//GEN-LAST:event_home1MouseClicked

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        if(evt.isPopupTrigger()){
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int coloum = source.columnAtPoint(evt.getPoint());

            if(! source.isRowSelected(row))
            source.changeSelection(row, coloum,false,false);

            popup_menu.show(evt.getComponent(),evt.getX(),evt.getY());

        }
    }//GEN-LAST:event_jPanel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel perawatantanaman;
    private javax.swing.JPopupMenu popup_menu;
    // End of variables declaration//GEN-END:variables

}
