/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author meri
 */
public class menu_perawatann extends javax.swing.JFrame {

    /**
     * Creates new form menu_perawatan
     */
    public menu_perawatann() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        perawatantanaman = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logout1 = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(244, 238, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(238, 149, 36)));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 475));

        perawatantanaman.setFont(new java.awt.Font("Tw Cen MT", 1, 26)); // NOI18N
        perawatantanaman.setForeground(new java.awt.Color(238, 149, 36));
        perawatantanaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rawat tanaman.png"))); // NOI18N
        perawatantanaman.setText("PERAWATAN TANAMAN");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(238, 149, 36)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(778, 298));

        jPanel1.setBackground(new java.awt.Color(244, 238, 238));
        jPanel1.setMinimumSize(new java.awt.Dimension(778, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(778, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(56, 87, 35));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 87, 35));
        jLabel2.setText("Berikut merupakan cara perawatan tanaman yang baik : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel3.setBackground(new java.awt.Color(56, 87, 35));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 87, 35));
        jLabel3.setText("Tanaman, baik yang hidup di dalam ruangan maupun di luar ruangan,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setBackground(new java.awt.Color(56, 87, 35));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(56, 87, 35));
        jLabel4.setText("dapat menjadi penghias tambahan yang cantik dirumah.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(56, 87, 35));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(56, 87, 35));
        jLabel5.setText("Perawatan dan pemeliharaannya umumnya mudah dilakukan dan, dengan perawatan ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setBackground(new java.awt.Color(56, 87, 35));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(56, 87, 35));
        jLabel6.setText("dan pemeliharaan yang tepat, tanaman dapat berkembang dengan baik.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/perawatan.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, 240));

        jPanel6.setBackground(new java.awt.Color(238, 149, 36));
        jPanel6.setPreferredSize(new java.awt.Dimension(350, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 620, 5));

        jLabel16.setBackground(new java.awt.Color(56, 87, 35));
        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(56, 87, 35));
        jLabel16.setText("tanaman cepat rusak. ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 620, 180, -1));

        jLabel17.setBackground(new java.awt.Color(56, 87, 35));
        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(135, 142, 108));
        jLabel17.setText("4. Antisipasi Hama dan Penyakit Pada Tanaman");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 920, -1, -1));

        jLabel18.setBackground(new java.awt.Color(56, 87, 35));
        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(56, 87, 35));
        jLabel18.setText("- Melakukan penyuraman selama dua kali sehari pada pagi dan sore hari");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel19.setBackground(new java.awt.Color(56, 87, 35));
        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(56, 87, 35));
        jLabel19.setText("- Siram tanaman secara merata agar tanaman dapat tumbuh dengan baik");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jLabel20.setBackground(new java.awt.Color(56, 87, 35));
        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(56, 87, 35));
        jLabel20.setText("- Hindari genangan air karena dapat menutup jalur oksigen dan membuat ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        jLabel21.setBackground(new java.awt.Color(56, 87, 35));
        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(56, 87, 35));
        jLabel21.setText("1. Melakukan Metode Penyiraman yang Tepat");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel22.setBackground(new java.awt.Color(56, 87, 35));
        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(56, 87, 35));
        jLabel22.setText("2. Memberikan Sinar Matahari Sesuai Kebutuhan");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        jLabel23.setBackground(new java.awt.Color(56, 87, 35));
        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(56, 87, 35));
        jLabel23.setText("Tempatkan tanaman pada tempat yang terkena sinar matahari agar kebutuhan");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, -1, -1));

        jLabel24.setBackground(new java.awt.Color(56, 87, 35));
        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(56, 87, 35));
        jLabel24.setText("fotosintesis terpenuhi. Namun yang harus diingat bahwa setiap tanaman memiliki");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, -1, -1));

        jLabel25.setBackground(new java.awt.Color(56, 87, 35));
        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(56, 87, 35));
        jLabel25.setText("kebutuhan akan sinar matahari yang berbeda, untuk itu harus diperhatikan pula");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, -1, -1));

        jLabel26.setBackground(new java.awt.Color(56, 87, 35));
        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(56, 87, 35));
        jLabel26.setText("seperti humidifier atau memberikan sumber air di sekeliling tanaman.");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 860, -1, -1));

        jLabel27.setBackground(new java.awt.Color(56, 87, 35));
        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(56, 87, 35));
        jLabel27.setText("sesuai dengan jenis tanamannya.");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, -1, -1));

        jLabel28.setBackground(new java.awt.Color(56, 87, 35));
        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(56, 87, 35));
        jLabel28.setText("Untuk kelembapan tanaman,bisa mengakali hal tersebut dengan alat bantu");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 840, -1, -1));

        jLabel29.setBackground(new java.awt.Color(56, 87, 35));
        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(56, 87, 35));
        jLabel29.setText("3. Kontrol Suhu dan Kelembapan yang Benar");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        jPanel3.setBackground(new java.awt.Color(238, 149, 36));
        jPanel3.setPreferredSize(new java.awt.Dimension(820, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jPanel3.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
        });
        jPanel3.add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perawatantanaman)
                .addGap(219, 219, 219))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(perawatantanaman)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
        new menu_pelanggan().setVisible(true);
    }//GEN-LAST:event_home1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_perawatann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_perawatann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_perawatann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_perawatann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_perawatann().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel perawatantanaman;
    // End of variables declaration//GEN-END:variables
}
