
package gui;

import java.text.SimpleDateFormat;
import java.util.Date;
import static gui.FormUtama.user1;

import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author meri
 */
public class menu_pelanggan extends javax.swing.JFrame {


    public menu_pelanggan() {
        initComponents();
    }
    
    public void tanggal(){
        SimpleDateFormat format = new SimpleDateFormat("EEEE dd MMMM yyyy");
        Date date = new Date();
        tgl.setText(format.format(date));
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_lihatproduk = new javax.swing.JButton();
        btn_perawatan = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();
        btn_hidroponik = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jButton1 = new javax.swing.JButton();
        btnpelanggan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(6, 125, 103));
        kGradientPanel1.setkGradientFocus(400);
        kGradientPanel1.setkStartColor(new java.awt.Color(176, 105, 25));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(770, 500));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(770, 550));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 230, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(6, 125, 103));
        jLabel5.setText("HOUSE OF PLANTS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 390, 50));

        jPanel2.setBackground(new java.awt.Color(240, 230, 229));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(6, 125, 103)));
        jPanel2.setForeground(new java.awt.Color(240, 230, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(176, 105, 25));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INFO TANAMAN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(176, 105, 25));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LIHAT PRODUK");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 170, -1));

        btn_lihatproduk.setBackground(new java.awt.Color(255, 255, 255));
        btn_lihatproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop.png"))); // NOI18N
        btn_lihatproduk.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_lihatproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihatprodukActionPerformed(evt);
            }
        });
        jPanel2.add(btn_lihatproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 170, 120));

        btn_perawatan.setBackground(new java.awt.Color(255, 255, 255));
        btn_perawatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rawat tanaman.png"))); // NOI18N
        btn_perawatan.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_perawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perawatanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_perawatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 170, 120));

        btn_info.setBackground(new java.awt.Color(255, 255, 255));
        btn_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        btn_info.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 160, 120));

        btn_hidroponik.setBackground(new java.awt.Color(255, 255, 255));
        btn_hidroponik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hidroponik.png"))); // NOI18N
        btn_hidroponik.setPreferredSize(new java.awt.Dimension(120, 120));
        btn_hidroponik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hidroponikActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hidroponik, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, 120));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(176, 105, 25));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PERAWATAN TANAMAN");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(176, 105, 25));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HIDROPONIK");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 500, 340));

        tgl.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        tgl.setForeground(new java.awt.Color(6, 125, 103));
        tgl.setText("Senin 5 Maret 2020");
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 250, -1));

        kButton1.setText("LOGOUT");
        kButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(6, 125, 103));
        kButton1.setkEndColor(new java.awt.Color(204, 204, 0));
        kButton1.setkHoverForeGround(new java.awt.Color(6, 125, 103));
        kButton1.setkHoverStartColor(new java.awt.Color(6, 125, 103));
        kButton1.setkSelectedColor(new java.awt.Color(6, 125, 103));
        kButton1.setkStartColor(new java.awt.Color(255, 51, 51));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 150, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_whatsapp_50px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btnpelanggan.setBackground(new java.awt.Color(255, 255, 255));
        btnpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pelanggan.png"))); // NOI18N
        btnpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpelangganActionPerformed(evt);
            }
        });
        jPanel1.add(btnpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 125, 103));
        jLabel1.setText("   TENTANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 125, 103));
        jLabel2.setText("CONTACT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 530));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged

    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed

    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btn_lihatprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihatprodukActionPerformed
//        Transaksi frm = new Transaksi();
//        Transaksi.txKasir.setText(user1.getText());
//        frm.setTitle("TRANSAKSI");
//        frm.setVisible(true); 
        new menu_produk().setVisible(true);


    }//GEN-LAST:event_btn_lihatprodukActionPerformed

    private void btn_perawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perawatanActionPerformed
        new menu_perawatann().setVisible(true);
    }//GEN-LAST:event_btn_perawatanActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        new menu_infotanaman().setVisible(true); 
            
    }//GEN-LAST:event_btn_infoActionPerformed

    private void btn_hidroponikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hidroponikActionPerformed
        new menu_hidroponik().setVisible(true);
    }//GEN-LAST:event_btn_hidroponikActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        new main_menu().setVisible(true);
        this.dispose();

     

    }//GEN-LAST:event_kButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            Desktop.getDesktop().browse(new URL("https://api.whatsapp.com/send?phone=6289656318741").toURI());
        } catch (MalformedURLException ex) {
            Logger.getLogger(menu_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(menu_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(menu_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpelangganActionPerformed
       
        new about().setVisible(true);
       
        
        
        
//        frmPelanggan frm = new frmPelanggan(this, rootPaneCheckingEnabled);
//        frm.setTitle("PELANGGAN");
//        frm.setVisible(true);

//        frmPelanggan frm = new frmPelanggan(this, rootPaneCheckingEnabled);
//        frm.setTitle("PELANGGAN");
//        frm.setVisible(true);
    }//GEN-LAST:event_btnpelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hidroponik;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_lihatproduk;
    private javax.swing.JButton btn_perawatan;
    private javax.swing.JButton btnpelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KButton kButton1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables

//    public static class totalBrg {
//
////        public static void setText(String string) {
////            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
////        }
//
//        public totalBrg() {
//        }
    }
