
package gui;

import com.jtattoo.plaf.mint.MintLookAndFeel;
import control.control_transaksi;
import control.koneksi;
import control.laporan;
import control.utama;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author meri
 */
public class Transaksi extends javax.swing.JFrame {
    control_transaksi ct;
    laporan lp;
    koneksi db;
    utama ut;
    

    public String kode_barang;
    public String nama_barang;
    public String keterangan;
    public static int qty;
    public static int harga;
    public static int stok;
    public int total;
   
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
//        Dimension dmax = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setMaximumSize(dmax);
////        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        this.setSize(dmax.width,dmax.height);
//        this.setLocationRelativeTo(null);
   
        db = new koneksi();
        ct = new control_transaksi();
        lp = new laporan();
        ut = new utama();
        tbPengeluaran.setModel(ct.model);
        ct.tampilPengeluaran("", "", 0, 0, 0);
        ct.noFak();
        setTanggal();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPengeluaran = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txqty = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txpelanggan = new javax.swing.JTextField();
        txNofak = new javax.swing.JTextField();
        txtotal2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCariPlg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txGrandTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txDiskon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txKembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txidPelanggan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tanggall = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        tampilTTL = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txKasir = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(225, 205, 92));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(240, 230, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(6, 125, 103)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Qty", "Total"
            }
        ));
        tbPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPengeluaran);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 590, 100));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ITEM BARANG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 16))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel5.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, 34));

        btnSimpan.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel5.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, 35));

        btnhapus.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel5.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 80, 35));

        btncancel.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.setEnabled(false);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 80, 35));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setText("KODE BARANG");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txkode.setEditable(false);
        txkode.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel5.add(txkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 35));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("NAMA BARANG");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txnama.setEditable(false);
        txnama.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel5.add(txnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 230, 35));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("QTY");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        txqty.setEditable(false);
        txqty.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txqtyKeyTyped(evt);
            }
        });
        jPanel5.add(txqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 70, 35));

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_40px.png"))); // NOI18N
        btnCari.setEnabled(false);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel5.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 58, 35));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 880, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEMBAYARAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txpelanggan.setEditable(false);
        txpelanggan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txpelanggan.setText("UMUM");
        jPanel1.add(txpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 32));

        txNofak.setEditable(false);
        txNofak.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txNofak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNofakActionPerformed(evt);
            }
        });
        jPanel1.add(txNofak, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 32));

        txtotal2.setEditable(false);
        txtotal2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel1.add(txtotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 140, 32));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setText("No. Faktur");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setText("Nama Pelanggan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnCariPlg.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnCariPlg.setText("CARI");
        btnCariPlg.setEnabled(false);
        btnCariPlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPlgActionPerformed(evt);
            }
        });
        jPanel1.add(btnCariPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 32));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Sub Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 16, -1, -1));

        txGrandTotal.setEditable(false);
        txGrandTotal.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel1.add(txGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 140, 32));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("Diskon (%)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 75, -1, -1));

        txDiskon.setEditable(false);
        txDiskon.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txDiskon.setText("0");
        txDiskon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txDiskonCaretUpdate(evt);
            }
        });
        jPanel1.add(txDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, 32));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setText("Grand Total");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 143, -1, -1));

        txBayar.setEditable(false);
        txBayar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txBayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txBayarCaretUpdate(evt);
            }
        });
        jPanel1.add(txBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 160, 32));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setText("Bayar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        txKembali.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txKembali.setEnabled(false);
        jPanel1.add(txKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 160, 32));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setText("Kembali");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        btnCetak.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnCetak.setText("CETAK NOTA");
        btnCetak.setEnabled(false);
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 117, 40));

        btnSave.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnSave.setText("SIMPAN");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 117, 40));

        btnReset.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnReset.setText("RESET");
        btnReset.setEnabled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 115, 40));

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 115, 40));

        txidPelanggan.setEditable(false);
        txidPelanggan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txidPelanggan.setText("P0001");
        jPanel1.add(txidPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 32));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel17.setText("ID Pelanggan");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 880, 219));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 40)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(6, 125, 103));
        jLabel13.setText("TRANSAKSI");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tanggall.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        tanggall.setForeground(new java.awt.Color(6, 125, 103));
        tanggall.setText("2020-03-28");
        jPanel3.add(tanggall, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(6, 125, 103));
        jLabel15.setText("Tanggal :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 102));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampilTTL.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        tampilTTL.setForeground(new java.awt.Color(255, 255, 255));
        tampilTTL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tampilTTL.setText("0");
        kGradientPanel1.add(tampilTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 30));

        jPanel3.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 270, 60));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(6, 125, 103));
        jLabel16.setText("Kasir :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        txKasir.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        txKasir.setForeground(new java.awt.Color(6, 125, 103));
        txKasir.setText("0000");
        jPanel3.add(txKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        frmCariBarang frm = new frmCariBarang(null, true,"Transaksi");
        frm.setTitle("PILIH BARANG");
        frm.setVisible(true);
      
       
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        
        btnCari.setEnabled(true);
        btnNew.setEnabled(false);
        btncancel.setEnabled(true);
       

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       
        kode_barang = txkode.getText();
        nama_barang = txnama.getText();
        qty = Integer.parseInt(txqty.getText());
        total = harga*qty;
        int total1 = 0;
        int subTotal = 0;
        int hargajual;
        int qty1;
        int total2 = 0;
        
         if(txqty.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "ISI QTY TERLEBIH DAHULU");
        }else if(qty>=stok){
             JOptionPane.showMessageDialog(this, "STOK TIDAK MENCUKUPI");
        }else{
            ct.tampilPengeluaran(kode_barang, nama_barang, harga, qty, total);
            txkode.setText("");
            txnama.setText("");
            txqty.setText("");
            for(int n =0;n<tbPengeluaran.getRowCount();n++){
                hargajual = (int) tbPengeluaran.getValueAt(n, 2);
                qty1 = (int) tbPengeluaran.getValueAt(n, 3);
                total1 = hargajual*qty;
                total2 = (int) tbPengeluaran.getValueAt(n, 4);
                subTotal += total2;
                
            }
            tampilTTL.setText(Integer.toString(subTotal));
            txtotal2.setText(Integer.toString(subTotal));
            txDiskon.setText("0");
            
            }
            btnNew.setEnabled(true);
            btnCari.setEnabled(false);
            btnSimpan.setEnabled(false);
            btncancel.setEnabled(false);
            txDiskon.setEditable(true);
            txBayar.setEditable(true);
            btnCariPlg.setEnabled(true);
            txqty.setEditable(false);
            txqty.setText("");
            txBayar.requestFocus();
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txDiskonCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txDiskonCaretUpdate
        
        if(txDiskon.getText().length()>0){
            int subtotal = Integer.parseInt(txtotal2.getText());
            int diskon = Integer.parseInt(txDiskon.getText());
            int ndiskon = subtotal*diskon/100;
            int total = subtotal - ndiskon;
            txGrandTotal.setText(Integer.toString(total));
           
        }
    }//GEN-LAST:event_txDiskonCaretUpdate

    private void txBayarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txBayarCaretUpdate
        
        if(txBayar.getText().length()>0){
            int bayar = Integer.parseInt(txBayar.getText());
            int total = bayar-Integer.parseInt(txGrandTotal.getText());
            txKembali.setText(Integer.toString(total));
            
            btnSave.setEnabled(true);
            btnReset.setEnabled(true);
          
            
        }
    }//GEN-LAST:event_txBayarCaretUpdate

    private void btnCariPlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPlgActionPerformed
        
        frmCariBarang frm = new frmCariBarang(this, true, "Pelanggan");
        frm.setTitle("PELANGGAN");
        frm.setVisible(true);
    }//GEN-LAST:event_btnCariPlgActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        String nofak = txNofak.getText();
        String kasir = txKasir.getText();
        String id_pelanggan = txidPelanggan.getText();
        String pelanggan = txpelanggan.getText();
        int total = Integer.parseInt(txGrandTotal.getText());
        int diskon = Integer.parseInt(txDiskon.getText());
        int bayar = Integer.parseInt(txBayar.getText());
        int kembali = Integer.parseInt(txKembali.getText());
      

       String tanggal = tanggall.getText();
       if(bayar<total){
           JOptionPane.showMessageDialog(rootPane, "PEMBAYARAN KURANG");
       }else{
            for(int n = 0;n<tbPengeluaran.getRowCount();n++){
            try {
                String kode_barang = (String) tbPengeluaran.getValueAt(n, 0);
                String nama_barang = (String) tbPengeluaran.getValueAt(n, 1);
                int harga = (int) tbPengeluaran.getValueAt(n, 2);
                int qty = (int) tbPengeluaran.getValueAt(n, 3);
                int totall = (int) tbPengeluaran.getValueAt(n, 4);
                db.setKoneksi();
                String sqli = "SELECT stok from masterbarang where kode_barang = '"+kode_barang+"'";
                Statement st = db.getKoneksi().createStatement();
                ResultSet rs = st.executeQuery(sqli);
                while(rs.next()){
                    int stok = rs.getInt("stok");
                    int sisa = stok - qty;
                    ct.updateStok(sisa, kode_barang);
                    
                }
                try {
                    ct.insertBarang(nofak, kode_barang, nama_barang, harga, qty, totall);
                } catch (SQLException ex) {
                    Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       
        
        try {
            ct.simpanPenjualan(nofak,kasir,id_pelanggan, pelanggan, diskon,total,bayar,kembali,tanggal);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI SIMPAN");

//            ct.noFak();
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        } 
      
        
         btnSave.setEnabled(false);
         btnCetak.setEnabled(true);
         btnCariPlg.setEnabled(false);
         btnNew.setEnabled(false);
       }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
    
        btncancel.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnNew.setEnabled(true);
        btnCari.setEnabled(false);
        btnhapus.setEnabled(false);
        txqty.setEditable(false);
        txqty.setText("");
        tbPengeluaran.clearSelection();
    }//GEN-LAST:event_btncancelActionPerformed

    private void tbPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPengeluaranMouseClicked
     
        btnhapus.setEnabled(true);
        btnSimpan.setEnabled(false);
        btncancel.setEnabled(true);
    }//GEN-LAST:event_tbPengeluaranMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        
    int row = tbPengeluaran.getSelectedRow();
        ct.model.removeRow(row);
        btnhapus.setEnabled(false);
        btncancel.setEnabled(false);
        btnNew.setEnabled(true);
        btnCari.setEnabled(false);
//        tampilTTL.setText("0");
//        txtotal2.setText("");
//        txGrandTotal.setText("");
        int subTotal = 0;
        for(int n =0;n<tbPengeluaran.getRowCount();n++){
            int hargajual = (int) tbPengeluaran.getValueAt(n, 2);
            int  qty1 = (int) tbPengeluaran.getValueAt(n, 3);
            int  total1 = hargajual*qty;
            int total2 = (int) tbPengeluaran.getValueAt(n, 4);
                  
            subTotal += total2;
                
            }
            tampilTTL.setText(Integer.toString(subTotal));
            txtotal2.setText(Integer.toString(subTotal));
            txDiskon.setText("0");
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txNofakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNofakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNofakActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        lp.printNota(txNofak.getText());
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       
        ct.model.removeRow(0);
        tampilTTL.setText("0");
        tbPengeluaran.removeAll();
        ct.noFak();
        txpelanggan.setText("UMUM");
        txDiskon.setText("0");
        txtotal2.setText("");
        txGrandTotal.setText("");
        txBayar.setText("");
        txKembali.setText("");
        txBayar.setEditable(false);
        txDiskon.setEditable(false);
        ct.model.setRowCount(0);
        btnCetak.setEnabled(false);
        btnReset.setEnabled(false);
        btnCariPlg.setEnabled(false);
        btnSave.setEnabled(false);
        btnCetak.setEnabled(false);
        btnNew.setEnabled(true);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
//       FormUtama frm = new FormUtama();
//       dispose();
       FormUtama.user1.setText(txKasir.getText());
//       frm.setVisible(true);
         ut.tampilCountTrx();
         dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
         ut.tampilCountTrx();
        
    }//GEN-LAST:event_formWindowClosing

    private void txqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txqtyKeyTyped
        
        if(txqty.getText().length()==5){
            evt.consume();
        }
    }//GEN-LAST:event_txqtyKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Transaksi().setVisible(true);
            }
        });
    }
    
    public void setTanggal(){
      Date tgl = new Date();
      SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
      tanggall.setText(format.format(tgl));
    }
 
    
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCariPlg;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    public static javax.swing.JButton btnSimpan;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel tampilTTL;
    private javax.swing.JLabel tanggall;
    private javax.swing.JTable tbPengeluaran;
    private javax.swing.JTextField txBayar;
    public static javax.swing.JTextField txDiskon;
    public static javax.swing.JTextField txGrandTotal;
    public static javax.swing.JLabel txKasir;
    private javax.swing.JTextField txKembali;
    public static javax.swing.JTextField txNofak;
    public static javax.swing.JTextField txidPelanggan;
    public static javax.swing.JTextField txkode;
    public static javax.swing.JTextField txnama;
    public static javax.swing.JTextField txpelanggan;
    public static javax.swing.JTextField txqty;
    public static javax.swing.JTextField txtotal2;
    // End of variables declaration//GEN-END:variables
}
